#!/usr/bin/env python

"""Merge the various output files generated by legacy-zeropoints.py to produce a
single zeropoints.fits file.

"""

from __future__ import division, print_function

import os
import argparse

